### ISSUE TITLE
Controlling ACs via Home app triggers errors

### ISSUE THREAD

**Issue by ovq** [nitaybz/homebridge-tado-ac#105]
I have linked a Hue tap to trigger some AC settings: Dry on, AC to 26 degrees, off

Randomly on any of these calls, I get these errors:

[2/16/2021, 12:24:45 AM] [TadoAC] Studio AC  -> Setting New State:
[2/16/2021, 12:24:45 AM] [TadoAC] {
  "termination": {
    "type": "TADO_MODE"
  },
  "setting": {
    "type": "AIR_CONDITIONING",
    "power": "OFF"
  }
}
(node:412) UnhandledPromiseRejectionWarning: TypeError: Cannot use 'in' operator to search for 'swing' in undefined
    at Object.tadoOverlay (/homebridge/node_modules/homebridge-tado-ac/tado/unified.js:209:15)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tado-ac/tado/StateHandler.js:71:33)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:412) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:412) UnhandledPromiseRejectionWarning: TypeError: Cannot use 'in' operator to search for 'swing' in undefined
    at Object.tadoOverlay (/homebridge/node_modules/homebridge-tado-ac/tado/unified.js:209:15)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tado-ac/tado/StateHandler.js:71:33)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:412) UnhandledPromiseRejectionWarning: TypeError: Cannot use 'in' operator to search for 'swing' in undefined
    at Object.tadoOverlay (/homebridge/node_modules/homebridge-tado-ac/tado/unified.js:209:15)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tado-ac/tado/StateHandler.js:71:33)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:412) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'autoFanSpeed' of undefined
    at Object.set (/homebridge/node_modules/homebridge-tado-ac/tado/StateHandler.js:59:78)
    at RotationSpeed.ACRotationSpeed (/homebridge/node_modules/homebridge-tado-ac/homekit/StateManager.js:421:27)
    at RotationSpeed.emit (events.js:315:20)
    at RotationSpeed.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at RotationSpeed.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:652:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1461:24
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1303:10)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
(node:412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[2/16/2021, 12:26:07 AM] [TadoAC] Studio AC  -> Setting New State:
[2/16/2021, 12:26:07 AM] [TadoAC] {
  "termination": {
    "type": "TADO_MODE"
  },
  "setting": {
    "type": "AIR_CONDITIONING",
    "power": "OFF"
  }
}
(node:412) UnhandledPromiseRejectionWarning: TypeError: Cannot use 'in' operator to search for 'swing' in undefined
    at Object.tadoOverlay (/homebridge/node_modules/homebridge-tado-ac/tado/unified.js:209:15)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tado-ac/tado/StateHandler.js:71:33)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)

**Comment by nitaybz** [comment]
Hey... I'm trying to investigate on this issue... it will greatly help if you could attach your config please and enable "Debug Logs" in the plugin settings and send over when Homebridge restarts.... make sure to hide any private information...

Also I would like to know... are those errors comes after you turned the device OFF? are you in Thermostatic mode?
