### ISSUE TITLE
No longer compatible with node.js 10

### ISSUE THREAD

**Issue by jadomski** [nitaybz/homebridge-tado-ac#124]
When installing under node.js 10, the following errors are thrown:

```
npm WARN notsup Unsupported engine for googleapis@109.0.1: wanted: {"node":">=12.0.0"} (current: {"node":"10.24.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: googleapis@109.0.1
npm WARN notsup Unsupported engine for googleapis-common@6.0.4: wanted: {"node":">=12.0.0"} (current: {"node":"10.24.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: googleapis-common@6.0.4
npm WARN notsup Unsupported engine for google-auth-library@8.7.0: wanted: {"node":">=12"} (current: {"node":"10.24.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: google-auth-library@8.7.0
npm WARN notsup Unsupported engine for gtoken@6.1.2: wanted: {"node":">=12.0.0"} (current: {"node":"10.24.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: gtoken@6.1.2
npm WARN notsup Unsupported engine for gcp-metadata@5.1.0: wanted: {"node":">=12"} (current: {"node":"10.24.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: gcp-metadata@5.1.0
npm WARN notsup Unsupported engine for gaxios@5.0.2: wanted: {"node":">=12"} (current: {"node":"10.24.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: gaxios@5.0.2
npm WARN notsup Unsupported engine for google-p12-pem@4.0.1: wanted: {"node":">=12.0.0"} (current: {"node":"10.24.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: google-p12-pem@4.0.1
```

Which in turn prevents the plugin from launching within homebridge itself:

```
====================
ERROR LOADING PLUGIN homebridge-tado-ac:
/home/user/.nvm/versions/node/v10.24.1/lib/node_modules/homebridge-tado-ac/node_modules/axios/index.js:1
import axios from './lib/axios.js';
       ^^^^^
 
SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/user/.nvm/versions/node/v10.24.1/lib/node_modules/homebridge-tado-ac/tado/api.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
====================
```

If possible it would be great to pin the versions of the dependancies so it can continue to run under node.js 10, but I'm unsure if this would break other things.

**Comment by nitaybz** [comment]
updated packages... it all should work now
