### ISSUE TITLE
Problem with my config.json file

### ISSUE THREAD

**Issue by Francis2b** [nitaybz/homebridge-tado-ac#16]
Hi,

I follow the readme everything went smooth but at the last step when runing homebridge I got this error taht says there is a problem with my config.json file:

```
[2017-12-22 10:57:27] Registering platform 'homebridge-tado-ac.TadoAC'
[2017-12-22 10:57:27] ---
[2017-12-22 10:57:27] There was a problem reading your config.json file.
[2017-12-22 10:57:27] Please try pasting your config.json file here to validate it: http://jsonlint.com
[2017-12-22 10:57:27] 
/usr/lib/node_modules/homebridge/lib/server.js:207
    throw err;
    ^

SyntaxError: Unexpected token : in JSON at position 11
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:201:19)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:57:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

Here is my config.json file:

```
"platforms": [
    {
        "platform": "TadoAC",
        "name": "Tado AC",
        "username": "xxxxxxxxxxxxxxxxxxx@xxxxxx.com",
        "password": "xxxxxxxxxxxxxx",
        "homeID": 12345,
        "weatherSensorsEnabled": true,
        "weatherPollingInterval": 10,
        "occupancySensorsEnabled": true,
        "occupancyPollingInterval": 10,
        "anyoneSensor": true,
        "tadoMode": "TADO_MODE",
        "durationInMinutes": 100,
        "autoOnly": false,
        "manualControl": true,
        "extraTemperatureSensor": true
    }
]


```

I tried copy past it and modify it in nano and I also tried to type the code myself but I still have the same error.

I'm runing homebridge on a Raspberry Pie 3 and I'm working on it through Terminal on my mac

Thanks for your help!

**Comment by nitaybz** [comment]
Hey @Francis2b !
is this all your config? cause if so it's wrong... it should look like that:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CD:21:43:67:89:90",
        "port": 51827,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file",

    "platforms": [
    {
        "platform": "TadoAC",
        "name": "Tado AC",
        "username": "xxxxxxxxxxxxxxxxxxx@xxxxxx.com",
        "password": "xxxxxxxxxxxxxx",
        "homeID": 12345,
        "weatherSensorsEnabled": true,
        "weatherPollingInterval": 10,
        "occupancySensorsEnabled": true,
        "occupancyPollingInterval": 10,
        "anyoneSensor": true,
        "tadoMode": "TADO_MODE",
        "durationInMinutes": 100,
        "autoOnly": false,
        "manualControl": true,
        "extraTemperatureSensor": true
    }
   ]
}

```

**Comment by nitaybz** [comment]
try to look more at homebridge wiki to know exactly how your config file should look like...

**Comment by Francis2b** [comment]
Hi, @nitaybz 

Yes it was the problem I figure it out maybe 10mins just before you answer me The 1st part of the json was missing.

Now it's working but I have another problem I'll open a new ticket
