### ISSUE TITLE
Option to remove fan as accesories

### ISSUE THREAD

**Issue by barelyanything** [nitaybz/homebridge-tado-ac#24]
Hi, thanks for making the plugin, I love it!
I wonder if it is possible to disable fan as accesories as an option (as I imagine there must be people who use rely on this), because I have a dyson at home and use it as a fan. But after I upgraded my plugin. I found that when I ask Siri to “Turn on the fan”, it turns on the fan in the AC instead of my fan.

Thanks!

**Comment by nitaybz** [comment]
it's possible, and make sense!... I'll try to make it as soon as I have time

**Comment by nitaybz** [comment]
Hey @barelyanything !
I created the option for you
can you try install from github:
`npm install -g https://github.com/nitaybz/homebridge-tado-ac#disable`

I can't test it at the moment so please if you can try it and tell me if it works...

all you need to do is to add `"disableFan": true`, to your config and restart

Let me know if it works well so I can update the main branch.

**Comment by barelyanything** [comment]
Unfortunately it didn’t work.
I have the latest version installed (2.2.13), My homebridge is running as a service, I went ahead and install the #disable branch from your command, and restart the service to see if it works before I update the config file. And homebridge cannot be started. 

I then reinstall the live version form bpm, homebridge starts fine.
Then I reinstall the debug branch again and added `”disableFan”: true`, restart and homebridge won’t start

Please let me know how can I help debugging this issue 👍 

Many thanks!

This is the service status message
```
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2018-03-27 21:24:23 HKT; 2s ago
  Process: 10840 ExecStart=/usr/local/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, status=1/FAILURE)
 Main PID: 10840 (code=exited, status=1/FAILURE)

Mar 27 21:24:23 brian-pib2-1 homebridge[10840]:     at new TadoAccessory (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:579:21)
Mar 27 21:24:23 brian-pib2-1 homebridge[10840]:     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:
Mar 27 21:24:23 brian-pib2-1 homebridge[10840]:     at emitNone (events.js:110:20)
Mar 27 21:24:23 brian-pib2-1 homebridge[10840]:     at IncomingMessage.emit (events.js:207:7)
Mar 27 21:24:23 brian-pib2-1 homebridge[10840]:     at endReadableNT (_stream_readable.js:1059:12)
Mar 27 21:24:23 brian-pib2-1 homebridge[10840]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
Mar 27 21:24:23 brian-pib2-1 homebridge[10840]:     at process._tickCallback (internal/process/next_tick.js:180:9)
Mar 27 21:24:23 brian-pib2-1 systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 21:24:23 brian-pib2-1 systemd[1]: homebridge.service: Unit entered failed state.
Mar 27 21:24:23 brian-pib2-1 systemd[1]: homebridge.service: Failed with result 'exit-code'.
```

This is the journalctl log
```
Mar 27 21:44:32 brian-pib2-1 homebridge[11041]: [2018-3-27 21:44:32] [Tado AC] Found new Zone: Living room (1) ...
Mar 27 21:44:33 brian-pib2-1 homebridge[11041]: /usr/local/lib/node_modules/homebridge-tado-ac/index.js:579
Mar 27 21:44:33 brian-pib2-1 homebridge[11041]:     if (this.fanMode.fanSpeeds){
Mar 27 21:44:33 brian-pib2-1 homebridge[11041]:                     ^
Mar 27 21:44:33 brian-pib2-1 homebridge[11041]: TypeError: Cannot read property 'fanSpeeds' of undefined
Mar 27 21:44:33 brian-pib2-1 homebridge[11041]:     at new TadoAccessory (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:579:21)
Mar 27 21:44:33 brian-pib2-1 homebridge[11041]:     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:319:53)
Mar 27 21:44:33 brian-pib2-1 homebridge[11041]:     at emitNone (events.js:110:20)
Mar 27 21:44:33 brian-pib2-1 homebridge[11041]:     at IncomingMessage.emit (events.js:207:7)
Mar 27 21:44:33 brian-pib2-1 homebridge[11041]:     at endReadableNT (_stream_readable.js:1059:12)
Mar 27 21:44:33 brian-pib2-1 homebridge[11041]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
Mar 27 21:44:33 brian-pib2-1 homebridge[11041]:     at process._tickCallback (internal/process/next_tick.js:180:9)
Mar 27 21:44:33 brian-pib2-1 systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 21:44:33 brian-pib2-1 systemd[1]: homebridge.service: Unit entered failed state.
Mar 27 21:44:33 brian-pib2-1 systemd[1]: homebridge.service: Failed with result 'exit-code'.
```

**Comment by nitaybz** [comment]
I'll have to test it myself... I'll check later today, cause it seems like something is missing here in the logs

**Comment by barelyanything** [comment]
Thanks! From the journalctl log it seems that it’s related to `this.fanMode.fanSpeeds` ‘s property being `undefined`

**Comment by nitaybz** [comment]
try to reinstall...
i tried to do some easy fix

**Comment by barelyanything** [comment]
Thanks for your quick update! But
After applying 0b89a4ebc5cb39a30764925188ddf4415c9353e5
```
Mar 27 22:03:30 brian-pi2b-1 homebridge[925]: [2018-3-27 22:03:30] [Tado AC] Found new Zone: Living room (1) ...
Mar 27 22:03:31 brian-pi2b-1 homebridge[925]: /usr/local/lib/node_modules/homebridge-tado-ac/index.js:586
Mar 27 22:03:31 brian-pi2b-1 homebridge[925]:     if (this.fanMode.fanSpeeds && this.autoOnly && fanAutoFanExists) { lastFanOverlay.setting.fanSpeed = "AUTO" }
Mar 27 22:03:31 brian-pi2b-1 homebridge[925]:                     ^
Mar 27 22:03:31 brian-pi2b-1 homebridge[925]: TypeError: Cannot read property 'fanSpeeds' of undefined
Mar 27 22:03:31 brian-pi2b-1 homebridge[925]:     at new TadoAccessory (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:586:21)
Mar 27 22:03:31 brian-pi2b-1 homebridge[925]:     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:319:53)
Mar 27 22:03:31 brian-pi2b-1 homebridge[925]:     at emitNone (events.js:110:20)
Mar 27 22:03:31 brian-pi2b-1 homebridge[925]:     at IncomingMessage.emit (events.js:207:7)
Mar 27 22:03:31 brian-pi2b-1 homebridge[925]:     at endReadableNT (_stream_readable.js:1059:12)
Mar 27 22:03:31 brian-pi2b-1 homebridge[925]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
Mar 27 22:03:31 brian-pi2b-1 homebridge[925]:     at process._tickCallback (internal/process/next_tick.js:180:9)
Mar 27 22:03:31 brian-pi2b-1 systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 22:03:31 brian-pi2b-1 systemd[1]: homebridge.service: Unit entered failed state.
Mar 27 22:03:31 brian-pi2b-1 systemd[1]: homebridge.service: Failed with result 'exit-code'.
```

**Comment by nitaybz** [comment]
try again please

**Comment by barelyanything** [comment]
No luck

```
Mar 30 17:58:04 brian-pi2b-1 homebridge[4110]: [2018-3-30 17:58:04] [Tado AC] Found new Zone: Living room (1) ...
Mar 30 17:58:05 brian-pi2b-1 homebridge[4110]: /usr/local/lib/node_modules/homebridge-tado-ac/index.js:587
Mar 30 17:58:05 brian-pi2b-1 homebridge[4110]:     else if (this.fanMode.fanSpeeds) { lastFanOverlay.setting.fanSpeed = this.fanMode.fanSpeeds[1] }
Mar 30 17:58:05 brian-pi2b-1 homebridge[4110]:                          ^
Mar 30 17:58:05 brian-pi2b-1 homebridge[4110]: TypeError: Cannot read property 'fanSpeeds' of undefined
Mar 30 17:58:05 brian-pi2b-1 homebridge[4110]:     at new TadoAccessory (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:587:26)
Mar 30 17:58:05 brian-pi2b-1 homebridge[4110]:     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:319:53)
Mar 30 17:58:05 brian-pi2b-1 homebridge[4110]:     at emitNone (events.js:110:20)
Mar 30 17:58:05 brian-pi2b-1 homebridge[4110]:     at IncomingMessage.emit (events.js:207:7)
Mar 30 17:58:05 brian-pi2b-1 homebridge[4110]:     at endReadableNT (_stream_readable.js:1059:12)
Mar 30 17:58:05 brian-pi2b-1 homebridge[4110]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
Mar 30 17:58:05 brian-pi2b-1 homebridge[4110]:     at process._tickCallback (internal/process/next_tick.js:180:9)
Mar 30 17:58:05 brian-pi2b-1 systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mar 30 17:58:05 brian-pi2b-1 systemd[1]: homebridge.service: Unit entered failed state.
Mar 30 17:58:05 brian-pi2b-1 systemd[1]: homebridge.service: Failed with result 'exit-code'.
```

**Comment by nitaybz** [comment]
I fixed the API issue and added 2 new features to disable fans and/or humidity sensors... check the readme file for more info...
install the new version (2.3) at:
`sudo npm install -g homebridge-tado-ac`

Let me know that it works you

**Comment by barelyanything** [comment]
Thanks for the update! Now homebridge starts without issue! I've added the config to disable the fan and the AC fan is no longer listed as an accessories.

However whenever I try to control the AC after I included `"disableFan": true`. 

This happens:

```
Apr 01 11:13:49 brian-pi2b-1 homebridge[6401]: [2018-4-1 11:13:49] [Tado AC] Activating Living room AC
Apr 01 11:13:50 brian-pi2b-1 homebridge[6401]: /usr/local/lib/node_modules/homebridge-tado-ac/index.js:1300
Apr 01 11:13:50 brian-pi2b-1 homebridge[6401]:                 if (accessory.fanMode){accessory.FanService.getCharacteristic(Characteristic.Active).updateValue(Characteristic.Active.INACTIVE)}
Apr 01 11:13:50 brian-pi2b-1 homebridge[6401]:                                                            ^
Apr 01 11:13:50 brian-pi2b-1 homebridge[6401]: TypeError: Cannot read property 'getCharacteristic' of undefined
Apr 01 11:13:50 brian-pi2b-1 homebridge[6401]:     at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:1300:60)
Apr 01 11:13:50 brian-pi2b-1 homebridge[6401]:     at ontimeout (timers.js:469:11)
Apr 01 11:13:50 brian-pi2b-1 homebridge[6401]:     at tryOnTimeout (timers.js:304:5)
Apr 01 11:13:50 brian-pi2b-1 homebridge[6401]:     at Timer.listOnTimeout (timers.js:264:5)
Apr 01 11:13:50 brian-pi2b-1 systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Apr 01 11:13:50 brian-pi2b-1 systemd[1]: homebridge.service: Unit entered failed state.
Apr 01 11:13:50 brian-pi2b-1 systemd[1]: homebridge.service: Failed with result 'exit-code'.
```

This happens as soon as I interact with the AC

Many thanks for adding the capabilities.

**Comment by nitaybz** [comment]
try reinstall again... I think it should work well now

**Comment by barelyanything** [comment]
Awesome! it works perfect now! Sent you $20 bucks over PayPal!

**Comment by nitaybz** [comment]
Got it!
Thanks man! much appreciated!
You have no idea how time consuming this can be... :)

I'm glad it all worked out
