### ISSUE TITLE
{ Error: getaddrinfo EAI_AGAIN auth.tado.com:443

### ISSUE THREAD

**Issue by xxsoulxx** [nitaybz/homebridge-tado-ac#43]
Hey, plugin is running, after a time i get this error and homebridge crashes,  after HB reboot, it runs fine till it crashes again after a few hours or days.

{ Error: getaddrinfo EAI_AGAIN auth.tado.com:443
    at Object._errnoException (util.js:1022:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'auth.tado.com',
  host: 'auth.tado.com',
  port: 443 }
/usr/local/lib/node_modules/homebridge-tado-ac/index.js:66
                var lastToken = self.storage.getItem('Tado_Token');
                                     ^

TypeError: Cannot read property 'storage' of undefined
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:66:38)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Please Help, thanks :)

**Comment by nitaybz** [comment]
Are you running the latest version?

**Comment by xxsoulxx** [comment]
Yes 2.3.5 and i just updated HB.

BTW i,m using Tado AC control V2, i,m not sure if the error appeared because i did update HB,NPM and raspberry. It was working for a long time before i updated and just occasionally crashed. Now it crashes every few hours,.

EDIT : Just updated NPM now i have to check if the error persists.

**Comment by nitaybz** [comment]
I mean the last version of this plugin

Tado v2 should not cause this error

**Comment by xxsoulxx** [comment]
yes its 2.3.5 atm. After updating everything it works now, have to observe if the error appears again. But its looking good till now.
