### ISSUE TITLE
TypeError: Service.HeaterCooler is not a function

### ISSUE THREAD

**Issue by dawiz77** [nitaybz/homebridge-tado-ac#48]
[8/26/2018, 3:57:11 PM] [Tado AC] Initializing platform accessory 'My AC Tado'...
/usr/local/lib/node_modules/homebridge-tado-ac/index.js:676
        this.HeaterCoolerService = new Service.HeaterCooler(this.zoneName + " AC");
                                   ^

TypeError: Service.HeaterCooler is not a function
    at TadoAccessory.__dirname.TadoACplatform.TadoACplatform.accessories.async.waterfall.TadoAccessory.getServices (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:676:36)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:357:36)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:343:32)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at /usr/local/lib/node_modules/homebridge-tado-ac/index.js:481:22
    at /usr/local/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:473:16
    at next (/usr/local/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:5329:29)
    at /usr/local/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:969:16
    at /usr/local/lib/node_modules/homebridge-tado-ac/index.js:476:28
    at nextTask (/usr/local/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:5324:14)

**Comment by dawiz77** [comment]
This happens right after the plugin (correctly) identifies the zones set in the Tado app.

**Comment by dawiz77** [comment]
sorry, my own stupidity - the auto-update script for homebridge didn't work, I was running an old version. The plugin runs perfectly fine with the latest version.
