### ISSUE TITLE
Crashing again

### ISSUE THREAD

**Issue by taimurasad** [nitaybz/homebridge-tado-ac#51]
All of a sudden, Homebridge has started crashing due to this:

[2018-11-13 14:09:06] [Tado AC] Could not retrieve Temperature Unit, error:SyntaxError: Unexpected token < in JSON at position 0
[2018-11-13 14:09:06] [Tado AC] Fetching Temperature Unit failed - Trying again...
/usr/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:966
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /usr/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:966:32
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tado-ac/index.js:179:33)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

any help?

**Comment by jnchman** [comment]
Seems to be an issue with the Tado server side API.
Tado's official iOS app is also not loading.

**Comment by jnchman** [comment]
Seems like Tado fixed their servers.

**Comment by nitaybz** [comment]
I'm glad...
