### ISSUE TITLE
Crash in 3.0.5 (running 2 Tado units)

### ISSUE THREAD

**Issue by nicktmro** [nitaybz/homebridge-tado-ac#55]
Hi, 

I just updated to 3.0.5 today (and even tried with the latest git commit) and Tado-AC is crashing Homebridge on startup. It worked ok before the update (I was most likely on 2.x).

Environment:
- 2 Tado units (identical hardware for both Tado and AC units)
- config file below

```xml
"platforms":[
		{
			"platform": "TadoAC",
			"username": "abc@def.com",
			"password": "****",
			"weatherSensorsEnabled": true,
			"weatherPollingInterval": 30,
			"tadoMode": "TADO_MODE",
			"statePollingInterval" : 10
		}
]
```

```
[12/10/2018, 3:33:00 PM] Found new Zone: Living room (1) ...
[12/10/2018, 3:33:00 PM] Found new Zone: Bedroom (2) ...
[12/10/2018, 3:33:02 PM] Initializing platform accessory 'Living room Tado'...
/usr/local/lib/node_modules/homebridge-tado-ac/index.js:427
            .on('get', this.getActive.bind(this))
            ^

TypeError: Cannot read property 'on' of undefined
    at TadoAccessory.getServices (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:427:13)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:378:36)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:364:32)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at async.waterfall (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:308:17)
    at /usr/local/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:473:16
    at next (/usr/local/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:5329:29)
    at /usr/local/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:969:16
    at async.waterfall (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:294:24)
    at nextTask (/usr/local/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:5324:14)
    at next (/usr/local/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:5331:9)
    at /usr/local/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:969:16
    at async.waterfall (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:231:17)
    at nextTask (/usr/local/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:5324:14)
    at next (/usr/local/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:5331:9)
    at /usr/local/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:969:16
```

Is there something I can do to prevent the crash?

Cheers,
Nick

**Comment by nicktmro** [comment]
Update: version 2.3.5 does not crash (but I did take out the "statePollingInterval" parameter).

**Comment by nitaybz** [comment]
What version of homebridge do you use?

**Comment by nicktmro** [comment]
macOS
homebdrige 0.4.16 
Node v6.9.2

**Comment by nitaybz** [comment]
can you try and upgrade homebridge to the latest?

**Comment by nicktmro** [comment]
Sweet, that solved it! Thanks

**Comment by nitaybz** [comment]
Thanks... I'll update the minimum required
