### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by nicktmro** [nitaybz/homebridge-tado-ac#58]
I had a temporary internet issue and I wonder if that's what caused this crash (that brought down homebridge with it)...

```
{ Error: getaddrinfo ENOTFOUND auth.tado.com auth.tado.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'auth.tado.com',
  host: 'auth.tado.com',
  port: 443 }
/usr/local/lib/node_modules/homebridge-tado-ac/lib/tadoHelpers.js:43
                console.Error('Couldn\'t Get Tado Token! trying again in 10 seconds')
                        ^

TypeError: console.Error is not a function
    at Object.storeToken (/usr/local/lib/node_modules/homebridge-tado-ac/lib/tadoHelpers.js:43:25)
    at ClientRequest.https.request.on (/usr/local/lib/node_modules/homebridge-tado-ac/lib/tadoApi.js:32:13)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1022:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by nitaybz** [comment]
yes it is... fixed in 3.1.2
