### ISSUE TITLE
Cannot read property 'swings' 

### ISSUE THREAD

**Issue by kaiatkins** [nitaybz/homebridge-tado-ac#76]
^[[37m[4/21/2019, 3:48:06 PM]^[[39m Loaded config.json with 0 accessories and 1 platforms.
^[[37m[4/21/2019, 3:48:06 PM]^[[39m Loading 1 platforms...                                
^[[37m[4/21/2019, 3:48:06 PM]^[[39m ^[[36m[TadoAC]^[[39m Initializing TadoAC platform...
^[[37m[4/21/2019, 3:48:09 PM]^[[39m ^[[36m[TadoAC]^[[39m Found new Zone: Office (3) ... 
^[[37m[4/21/2019, 3:48:10 PM]^[[39m ^[[36m[TadoAC]^[[39m Initializing platform accessory 'Office Tado'...
^[[37m[4/21/2019, 3:48:10 PM]^[[39m ^[[1m^[[31mTypeError: Cannot read property 'swings' of undefined     
    at TadoAccessory.getServices (/homebridge/node_modules/homebridge-tado-ac/index.js:539:69)           
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:427:36)             
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:413:32)                  
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19             
    at async.waterfall (/homebridge/node_modules/homebridge-tado-ac/index.js:308:17)                
    at /homebridge/node_modules/async/dist/async.js:473:16                                    
    at next (/homebridge/node_modules/async/dist/async.js:5329:29)                          
    at /homebridge/node_modules/async/dist/async.js:969:16                                  
    at async.waterfall (/homebridge/node_modules/homebridge-tado-ac/index.js:294:24)        
    at nextTask (/homebridge/node_modules/async/dist/async.js:5324:14)^[[39m^[[22m  

config is just

        "platforms": [{
                "platform": "TadoAC",
                "username": "my email",
                "password": "my pw"
        }]
}

**Comment by kaiatkins** [comment]
@nitaybz i added             
"autoFanOnly": true,
"forceThermostat": true

and now seems to work

**Comment by nitaybz** [comment]
it's fixed with the last version 3.1.3
