### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by rafacampoamor** [nitaybz/homebridge-tado-ac#8]
Not sure if it's a Tado AC or home bridge issue. After a raspberry hardreset, I'm installing everything again, and I'm getting this when initiating Hombridge:

```
[2017-11-1 21:25:38] Loaded plugin: homebridge-tado-ac
[2017-11-1 21:25:38] Registering platform 'homebridge-tado-ac.TadoAC'
[2017-11-1 21:25:38] ---
[2017-11-1 21:25:38] Loaded config.json with 0 accessories and 1 platforms.
[2017-11-1 21:25:38] ---
[2017-11-1 21:25:38] Loading 1 platforms...
[2017-11-1 21:25:38] [Tado AC] Initializing TadoAC platform...
[2017-11-1 21:25:38] Loading 0 accessories...
[2017-11-1 21:25:38] [Tado AC] Found new Zone: Aire Acondicionado (2) ...
[2017-11-1 21:25:39] [Tado AC] Initializing platform accessory 'Aire Acondicionado Tado'...
[2017-11-1 21:25:39] [Tado AC] Initializing platform accessory 'Outside Temperature'...
[2017-11-1 21:25:39] [Tado AC] Initializing platform accessory 'User 1'...
[2017-11-1 21:25:39] [Tado AC] Initializing platform accessory 'User 2'...
[2017-11-1 21:25:39] [Tado AC] Initializing platform accessory 'User 3'...
[2017-11-1 21:25:39] [Tado AC] Initializing platform accessory 'Anyone'...
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:384
  var encodedPayload = (buffer.readUInt32BE(4) + (buffer.readUInt32BE(0) * Math.pow(2, 32))).toString(36).toUpperCase().padStart(9, '0');
                                                                                                                        ^

TypeError: (buffer.readUInt32BE(...) + (buffer.readUInt32BE(...) * Math.pow(...))).toString(...).toUpperCase(...).padStart is not a function
    at Bridge.Accessory.setupURI (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:384:121)
    at Server._printSetupInfo (/usr/lib/node_modules/homebridge/lib/server.js:600:32)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:128:8)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:381:14)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/lib/node_modules/homebridge-tado-ac/index.js:331:13
    at /usr/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:421:16
    at next (/usr/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:5302:29)
    at /usr/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:906:16
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tado-ac/index.js:324:29)
```

Do you have any idea why this is happening?

**Comment by nitaybz** [comment]
what version of homebridge are you using?

**Comment by nitaybz** [comment]
can you try to start homebridge with a different platform plugin and and let me know if it works?

**Comment by rafacampoamor** [comment]
Lastest

**Comment by nitaybz** [comment]
can it be because one of the names of the accessories contains special characters? for example, usernames for the occupancy sensor or Zone name for each device?

**Comment by rafacampoamor** [comment]
```
[2017-11-1 22:15:10] [Hue] Philips hue: 1 accessories
[2017-11-1 22:15:10] [Hue] Initializing platform accessory 'Philips hue'...
[2017-11-1 22:15:10] [Hue] Philips hue: 3 services
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
[2017-11-1 22:15:10] [Hue] (buffer.readUInt32BE(...) + (buffer.readUInt32BE(...) * Math.pow(...))).toString(...).toUpperCase(...).padStart is not a function
[2017-11-1 22:15:10] Homebridge is running on port 51826.
```

**Comment by nitaybz** [comment]
ok so it's a homebridge issue... did you install it in a different way than before?
maybe you missed a package or an outdated version of nodejs

**Comment by rafacampoamor** [comment]
I think I don't have any spacial character apart from a dot "."

**Comment by rafacampoamor** [comment]
And my version is homebridge 0.4.30

**Comment by nitaybz** [comment]
ok I did some digging... and apparently this version you installed is very very new, published 2 hours ago and include also new version of HAP-nodejs that was published 2 hours ago...
those line of code you have issues with are fresh code so it might be an issue with that release and it's too early to look for open issues...

I would suggest submitting an issue in both homebridge and hap-nodejs about this new issue and if you're impatient and want it to work now you can install an earlier release.. mine is 0.4.28 and working great!

hope I helped you :)

**Comment by rafacampoamor** [comment]
I just tried to force a newer version of node and it went even worse

```
$ homebridge
/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: The module '/usr/lib/node_modules/homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
´´´
¿Do you have any other idea?

Thanks!

**Comment by nitaybz** [comment]
```
npm uninstall -g homebridge
npm install -g homebridge@0.4.28
```

should solve your problems

**Comment by rafacampoamor** [comment]
A little off topic… I am getting this because of the node.js upgrade I forced… 

```
Error: The module '/usr/lib/node_modules/homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
´´´
How do I downgrade to the 6x version?

Thanks

**Comment by nitaybz** [comment]
you don't need to downgrade... this issue is saying that your homebridge is compiled with a different node js version and that you need to re-compile it...

by doing the commands above you will solve both issues...

**Comment by nitaybz** [comment]
I published your issue in the appropriate thread:
[https://github.com/nfarina/homebridge/issues/1588](https://github.com/nfarina/homebridge/issues/1588)

**Comment by rafacampoamor** [comment]
Thank you!

I don’t know why, but when reinstalling (using sudo) I get this:

gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/homebridge/node_modules/mdns/.node-gyp/8.9.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/homebridge/node_modules/mdns/.node-gyp"

**Comment by nitaybz** [comment]
try that:
```
npm uninstall -g --unsafe-perm homebridge
npm install -g --unsafe-perm homebridge@0.4.28
```

**Comment by rafacampoamor** [comment]
It seems to work now!!

Thanks a lot!!!

**Comment by nitaybz** [comment]
by the way... I'm not sure if you follow the thread in the link I sent you.
their gonna fix this issue...

**Comment by nitaybz** [comment]
so if you want to wait for the latest release it should happen soon
the new version will bring pairing homebridge with QR code

**Comment by rafacampoamor** [comment]
Once It’s working, I’m no hurry to update.

Thanks a lot!!

**Comment by nitaybz** [comment]
no probem :)
glad I could help
