### ISSUE TITLE
Cannot read property 'id' of null

### ISSUE THREAD

**Issue by jamitupya** [nitaybz/homebridge-tado-ac#83]
this is the error and you can see it SIGTERM's at the end as well.

[8/22/2019, 9:44:26 PM] TypeError: Cannot read property 'id' of null,
[8/22/2019, 9:44:25 PM] [Tado AC] Found new Zone: Air Conditioning (2) ...,
    at installations.find.device (/homebridge/node_modules/homebridge-tado-ac/index.js:172:89),
    at Array.find (<anonymous>),
    at zones.map.zone (/homebridge/node_modules/homebridge-tado-ac/index.js:170:60),
    at Array.map (<anonymous>),
    at tadoApi.getInstallations (/homebridge/node_modules/homebridge-tado-ac/index.js:169:39),
    at IncomingMessage.res.on (/homebridge/node_modules/homebridge-tado-ac/lib/tadoApi.js:348:17),
    at IncomingMessage.emit (events.js:203:15),
    at endReadableNT (_stream_readable.js:1145:12),
    at process._tickCallback (internal/process/next_tick.js:63:19),
[8/22/2019, 9:44:26 PM] Got SIGTERM, shutting down Homebridge...,
-U /homebridge -P /homebridge/node_modules -C

**Comment by jamitupya** [comment]
basically i have tried re-installing homebridge + the plugin. this used to work, however no longer :-(

**Comment by jamitupya** [comment]
basically caused by an incompletely setup device on my account, once completed, worked without this error
