### ISSUE TITLE
TypeError: zones.filter is not a function

### ISSUE THREAD

**Issue by cw1812** [nitaybz/homebridge-tado-ac#84]
any help on this?

TypeError: zones.filter is not a function
    at tadoApi.getZones (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:119:39)
    at IncomingMessage.res.on.e (/usr/local/lib/node_modules/homebridge-tado-ac/lib/tadoApi.js:118:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by nitaybz** [comment]
It's probably because your nose version is not updated.
Check version with
`node -v`

**Comment by cw1812** [comment]
I tried every version from version v6 to v12. All have same error code as above...

For info I can run homebridge without error if I do not call tado ac in config.json

**Comment by nitaybz** [comment]
You need to reinstall homebridge after updating mode. Otherwise it won't work

**Comment by cw1812** [comment]
Can you advise your test version of node and homebridge? I run tado ac homebridge on Raspbrian Stretch (Linux 9) for a year without any issue (appreciate your nice work) but now need to rebuild it.

**Comment by nitaybz** [comment]
any version above 8 is fine... and by reinstalling homebridge you won't affect your setup... to me it was pretty fast, update node and install homebridge again... make sure to backup your persist files, config and cached files

**Comment by nitaybz** [comment]
@cw1812 is it fixed for you?
