### ISSUE TITLE
Fahrenheit

### ISSUE THREAD

**Issue by alexsalex** [nitaybz/homebridge-tado-ac#86]
Crashed with error: Cannot read property 'fahrenheit' of undefined... )

**Comment by alexsalex** [comment]
```
[2019-11-24 20:48:50] [Tado] Living Room Current Mode is  FAN
[2019-11-24 20:48:50] [Tado] Living Room Current Temperature is 70.3ºF
[2019-11-24 20:48:50] TypeError: Cannot read property 'fahrenheit' of undefined
    at getCurrentStateResponse (/opt/node/lib/node_modules/homebridge-tado-ac/index.js:824:96)
    at getCallbacks.(anonymous function).callbacks.forEach.callback (/opt/node/lib/node_modules/homebridge-tado-ac/lib/tadoHelpers.js:251:33)
    at Array.forEach (<anonymous>)
    at tadoApi.getState (/opt/node/lib/node_modules/homebridge-tado-ac/lib/tadoHelpers.js:250:63)
    at IncomingMessage.res.on (/opt/node/lib/node_modules/homebridge-tado-ac/lib/tadoApi.js:217:17)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
[2019-11-24 20:48:50] Got SIGTERM, shutting down Homebridge...
```

**Comment by nitaybz** [comment]
set `"debug": true` in your config and send the logs again, which should add more details

**Comment by alexsalex** [comment]
```
[2019-11-26 22:50:43] [Tado] { tadoMode: 'HOME',
  geolocationOverride: false,
  geolocationOverrideDisableTime: null,
  preparation: null,
  setting:
   { type: 'AIR_CONDITIONING',
     power: 'ON',
     mode: 'COOL',
     temperature: { celsius: 20, fahrenheit: 68 } },
  overlayType: null,
  overlay: null,
  openWindow: null,
  nextScheduleChange: null,
  nextTimeBlock: { start: '2019-11-27T15:00:00.000Z' },
  link: { state: 'ONLINE' },
  activityDataPoints:
   { acPower:
      { timestamp: '2019-11-27T06:25:37.456Z',
        type: 'POWER',
        value: 'ON' } },
  sensorDataPoints:
   { insideTemperature:
      { celsius: 22.39,
        fahrenheit: 72.3,
        timestamp: '2019-11-27T06:42:36.096Z',
        type: 'TEMPERATURE',
        precision: [Object] },
     humidity:
      { type: 'PERCENTAGE',
        percentage: 44.3,
        timestamp: '2019-11-27T06:42:36.096Z' } } }
[2019-11-26 22:50:43] [Tado] Sending 4 callbacks to Bedroom Tado
[2019-11-26 22:50:43] [Tado] Bedroom Current Mode is  COOL
[2019-11-26 22:50:43] [Tado] Bedroom Target Temperature is 68ºF
[2019-11-26 22:50:43] [Tado] Bedroom Target Mode is  COOL
[2019-11-26 22:50:43] [Tado] Bedroom Current Temperature is 72.3ºF
[2019-11-26 22:50:43] [Tado] { tadoMode: 'HOME',
  geolocationOverride: false,
  geolocationOverrideDisableTime: null,
  preparation: null,
  setting:
   { type: 'AIR_CONDITIONING',
     power: 'ON',
     mode: 'FAN',
     fanSpeed: 'LOW' },
  overlayType: 'MANUAL',
  overlay:
   { type: 'MANUAL',
     setting:
      { type: 'AIR_CONDITIONING',
        power: 'ON',
        mode: 'FAN',
        fanSpeed: 'LOW' },
     termination:
      { type: 'MANUAL',
        typeSkillBasedApp: 'MANUAL',
        projectedExpiry: null } },
  openWindow: null,
  nextScheduleChange: null,
  nextTimeBlock: null,
  link: { state: 'ONLINE' },
  activityDataPoints:
   { acPower:
      { timestamp: '2019-11-22T22:34:40.992Z',
        type: 'POWER',
        value: 'ON' } },
  sensorDataPoints:
   { insideTemperature:
      { celsius: 20.89,
        fahrenheit: 69.6,
        timestamp: '2019-11-27T06:41:20.086Z',
        type: 'TEMPERATURE',
        precision: [Object] },
     humidity:
      { type: 'PERCENTAGE',
        percentage: 48.7,
        timestamp: '2019-11-27T06:41:20.086Z' } } }
[2019-11-26 22:50:43] [Tado] Sending 6 callbacks to Living Room Tado
[2019-11-26 22:50:43] [Tado] Living Room Fan Active State is 1
[2019-11-26 22:50:43] TypeError: tadoHelpers.returnFanFanspeedValue is not a function
    at getCurrentStateResponse (/opt/node/lib/node_modules/homebridge-tado-ac/index.js:1014:116)
    at getCallbacks.(anonymous function).callbacks.forEach.callback (/opt/node/lib/node_modules/homebridge-tado-ac/lib/tadoHelpers.js:251:33)
    at Array.forEach (<anonymous>)
    at tadoApi.getState (/opt/node/lib/node_modules/homebridge-tado-ac/lib/tadoHelpers.js:250:63)
    at IncomingMessage.res.on (/opt/node/lib/node_modules/homebridge-tado-ac/lib/tadoApi.js:217:17)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
[2019-11-26 22:50:43] Got SIGTERM, shutting down Homebridge...
```

**Comment by nitaybz** [comment]
I fixed the last error you presented... and it's different from the first one, you'll have to reinstall and post the logs again if you see anymore errors

**Comment by alexsalex** [comment]
pls, push it to npm

**Comment by nitaybz** [comment]
I did...

**Comment by alexsalex** [comment]
Got the fahrenheit error

**Comment by nitaybz** [comment]
ok... as I told you in the last detailed log it was a different error that was fixed... please share the detailed log of the Fahrenheit issue

**Comment by alexsalex** [comment]
```
[2019-11-27 23:59:46] [Tado] { tadoMode: 'HOME',
  geolocationOverride: false,
  geolocationOverrideDisableTime: null,
  preparation: null,
  setting:
   { type: 'AIR_CONDITIONING',
     power: 'ON',
     mode: 'FAN',
     fanSpeed: 'LOW' },
  overlayType: 'MANUAL',
  overlay:
   { type: 'MANUAL',
     setting:
      { type: 'AIR_CONDITIONING',
        power: 'ON',
        mode: 'FAN',
        fanSpeed: 'LOW' },
     termination:
      { type: 'MANUAL',
        typeSkillBasedApp: 'MANUAL',
        projectedExpiry: null } },
  openWindow: null,
  nextScheduleChange: null,
  nextTimeBlock: null,
  link: { state: 'ONLINE' },
  activityDataPoints:
   { acPower:
      { timestamp: '2019-11-22T22:34:40.992Z',
        type: 'POWER',
        value: 'ON' } },
  sensorDataPoints:
   { insideTemperature:
      { celsius: 23.39,
        fahrenheit: 74.1,
        timestamp: '2019-11-28T07:57:08.142Z',
        type: 'TEMPERATURE',
        precision: [Object] },
     humidity:
      { type: 'PERCENTAGE',
        percentage: 41.7,
        timestamp: '2019-11-28T07:57:08.142Z' } } }
[2019-11-27 23:59:46] [Tado] Sending 6 callbacks to Living Room Tado
[2019-11-27 23:59:46] [Tado] Living Room Fan Active State is 1
[2019-11-27 23:59:46] [Tado] Living Room Fan Rotation Speed is LOW 33.33
[2019-11-27 23:59:46] TypeError: Cannot read property 'fahrenheit' of undefined
    at getCurrentStateResponse (/opt/node/lib/node_modules/homebridge-tado-ac/index.js:824:96)
    at getCallbacks.(anonymous function).callbacks.forEach.callback (/opt/node/lib/node_modules/homebridge-tado-ac/lib/tadoHelpers.js:251:33)
    at Array.forEach (<anonymous>)
    at tadoApi.getState (/opt/node/lib/node_modules/homebridge-tado-ac/lib/tadoHelpers.js:250:63)
    at IncomingMessage.res.on (/opt/node/lib/node_modules/homebridge-tado-ac/lib/tadoApi.js:217:17)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
[2019-11-27 23:59:46] Got SIGTERM, shutting down Homebridge...
[2019-11-27 23:59:47] [Tado] { tadoMode: 'HOME',
  geolocationOverride: false,
  geolocationOverrideDisableTime: null,
  preparation: null,
  setting:
   { type: 'AIR_CONDITIONING',
     power: 'ON',
     mode: 'COOL',
     temperature: { celsius: 20, fahrenheit: 68 } },
  overlayType: 'MANUAL',
  overlay:
   { type: 'MANUAL',
     setting:
      { type: 'AIR_CONDITIONING',
        power: 'ON',
        mode: 'COOL',
        temperature: [Object] },
     termination:
      { type: 'MANUAL',
        typeSkillBasedApp: 'MANUAL',
        projectedExpiry: null } },
  openWindow: null,
  nextScheduleChange: null,
  nextTimeBlock: { start: '2019-11-28T15:00:00.000Z' },
  link: { state: 'ONLINE' },
  activityDataPoints:
   { acPower:
      { timestamp: '2019-11-28T04:51:58.313Z',
        type: 'POWER',
        value: 'ON' } },
  sensorDataPoints:
   { insideTemperature:
      { celsius: 23.74,
        fahrenheit: 74.73,
        timestamp: '2019-11-28T07:59:04.573Z',
        type: 'TEMPERATURE',
        precision: [Object] },
     humidity:
      { type: 'PERCENTAGE',
        percentage: 39.6,
        timestamp: '2019-11-28T07:59:04.573Z' } } }
[2019-11-27 23:59:47] [Tado] Sending 4 callbacks to Bedroom Tado
[2019-11-27 23:59:47] [Tado] Bedroom Target Temperature is 68ºF
[2019-11-27 23:59:47] [Tado] Bedroom Target Mode is  COOL
[2019-11-27 23:59:47] [Tado] Bedroom Current Temperature is 74.73ºF
[2019-11-27 23:59:47] [Tado] Bedroom Current Mode is  COOL
```

**Comment by nitaybz** [comment]
reinstall and try again please

**Comment by alexsalex** [comment]
fixed

**Comment by nitaybz** [comment]
I'm glad :)
