### ISSUE TITLE
Crash started today (17 MAR 2020)

### ISSUE THREAD

**Issue by mwkchan** [nitaybz/homebridge-tado-ac#90]
New crash, no changes in config.

---
log:

[3/17/2020, 1:19:04 AM] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>:null:null)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tado-ac/lib/tadoApi.js:61:26)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

[3/17/2020, 1:19:04 AM] Got SIGTERM, shutting down Homebridge...

-----
config:

        {
            "platform": "TadoAC",
            "username": "xxxx",
            "password": "xxxx",
            "tadoMode": "TADO_MODE",
            "statePollingInterval": 10,
            "manualControlSwitch": true,
            "occupancySensorsEnabled": true
        },

**Comment by nitaybz** [comment]
Do you have the latest version installed? It should not crash, even when Tado servers are done.
It seems like Tado servers are not working at the moment... can you operate through the tado app?

**Comment by mwkchan** [comment]
You are right, Tado server not working.

The plug-in I installed is homebridge-tado-ac v3.2.5

**Comment by nitaybz** [comment]
Alright I'll check that error
