### ISSUE TITLE
New "Manuel" error after upgraded to Homebridge 1.0

### ISSUE THREAD

**Issue by mwkchan** [nitaybz/homebridge-tado-ac#92]
Today I upgraded Homebridge to 1.0 and found the following error when I switched off the Manual mode of TADO.

[4/27/2020, 10:20:35 PM] [TadoAC] Turning OFF Living Room Manual Control
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>:null:null)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tado-ac/lib/tadoApi.js:249:33)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Couldn't Parse strData:

**Comment by nitaybz** [comment]
it seems like I missing the most important part in the log, the "strData" which should be following the last line you posted

**Comment by mwkchan** [comment]
It got nothing there, I just triggered the manual switch again. Here's the log:

[5/2/2020, 4:58:25 PM] [TadoAC] Living Room Target Temperature is 27ºC
[5/2/2020, 4:58:25 PM] [TadoAC] Living Room Tado *New State* - Room Temperature - 26.77 ºC
[5/2/2020, 4:58:25 PM] [TadoAC] Living Room Tado *New State* - Relative Humidity - 47.9 %
[5/2/2020, 4:58:42 PM] [TadoAC] Turning OFF Living Room Manual Control
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>:null:null)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tado-ac/lib/tadoApi.js:249:33)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Couldn't Parse strData:

[5/2/2020, 4:58:46 PM] [TadoAC] Living Room Tado (Fan) *New State* - Updating Manual - OFF
[5/2/2020, 4:58:48 PM] [TadoAC] Turning ON Living Room Manual Control
[5/2/2020, 4:58:48 PM] [TadoAC] Setting new state on Living Room -->
[5/2/2020, 4:58:48 PM] [TadoAC] {
  setting: {
    type: 'AIR_CONDITIONING',
    power: 'ON',
    mode: 'COOL',
    temperature: { celsius: 27, fahrenheit: 80.6 }
  },
  termination: { type: 'TADO_MODE' }
}
[5/2/2020, 4:58:48 PM] [TadoAC] Living Room Tado (Fan) *New State* - Updating Manual - ON
[5/2/2020, 4:58:54 PM] [TadoAC] Living Room Humidity is 47.9%

**Comment by nitaybz** [comment]
Should be fixed in version 4 !

Hope you can approve that it works as expected

**Comment by nitaybz** [comment]
on version 4 the plugin was completely refactored, therefore the problem will not occur on this version.
If other problems occur on version 4, please open a new ticket.
closing...
